### PR TITLE
Update docs to reflect installing controller on user's namespace, pri…

### PR DESCRIPTION
**Pull request by ashahba**
Update docs to reflect installing controller on user's namespace, prior to using KVC.
Since currently it's not clear for the users that controller needs to be installed per namespace.

### CODE REVIEW

**Comment by ashahba** [comment]
@balajismaniam are we good with this PR?

**Comment by ashahba** [comment]
@balajismaniam This should be good now, but I'm not sure why `kubeflow-experimental-kvc-presubmit` is failing!

**Comment by balajismaniam** [comment]
It is failing because we have not setup prow for KVC yet.

**Pull request merged**
